apiVersion: v1
kind: Pod
metadata:
  name: initdemo1
  namespace: staging  # Add the namespace here
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"

  initContainers:
    - name: install-nginx
      image: busybox
      command: ["wget", "-O", "/work-dir/index.html", "http://info.cern.ch"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "20m"
        limits:
          memory: "64Mi"
          cpu: "40m"
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"

    - name: install-busybox
      image: busybox
      command: ["wget", "-O", "/work-dir/index.html", "http://info.cern.ch"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "20m"
        limits:
          memory: "64Mi"
          cpu: "40m"
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"

  volumes:
    - name: workdir
      emptyDir: {}
