apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: container1
        image: nginx
      - name: container2
        image: busybox
      restartPolicy: OnFailure
